### ISSUE TITLE
Vulnerable to SQL injection

### ISSUE THREAD

**Issue by ojhaujjwal** [goalio/GoalioForgotPasswordDoctrineORM#7]
I may me wrong but I think that the module is vulnerable to SQL injection because of this line https://github.com/goalio/GoalioForgotPasswordDoctrineORM/blob/master/src/GoalioForgotPasswordDoctrineORM/Mapper/Password.php#L54

**Comment by pdobrigkeit** [comment]
Dude, if you are so smart, then start submitting pull requests. I do not use this module myself, but I made it by request of other users. It is very easy to fix this stuff if you are keen on it and it seems you have a lot of time on your hands if you are able to read all the source code. But in that case you could have noticed that the $userId var in that mapper is fetched from the DB and not submitted externally.

**Comment by ojhaujjwal** [comment]
@pdobrigkeit  So it means that you have started to hate getting issues on your repositories!
I was just trying to help. So why are you being offensive?

**Comment by pdobrigkeit** [comment]
Because one of your first issues that you opened I felt was quite offensive. Opening an issue just saying "Seriously, where are the tests?" is coming on me like saying: "You are stupid, you don't know what you are doing, whatever". I would never say that to a person I don't know because there probably are reasons why there are no tests and such. I build these modules because I thought they might be helpful to others and not because I want people telling me "You are missing this and you are missing that" 

I could have just done that and bragged in the ZfcUser module why these functions are not available, instead I just did something about it and I expect people to do the same.

**Comment by ojhaujjwal** [comment]
@pdobrigkeit .I think i should open another issue, PR to be precise.  Your documentations are outdated. I think you should update your README.md to include the last comment!

I did not know you disliked my issue regarding the tests. You should have told me at that time just like i did now.
Chill man
